### ISSUE TITLE
Safari Version 10.1  is Gif instead of CSS Grid

### ISSUE THREAD

**Issue by sunright** [purplecones/css-grid-playground#2]
Mirza,

I really like the idea here of React and CSS Grid...dear say it might be the first example of how dynamic the web can and will be ....Great Job! 

One the first sites I visited was your site (on the entire internet with Safari 10.1 browser) and it showed Gif instead all your CSS Grid brilliance :-(

I sadly do not know how to use react yet to help you fix the issue....so all I can do is report the issue .

Great Job this site will really help people....I feel a clever UI and this could nice CMS tool :-) ...let me know if your interested.

We learn by sharing what we know
Robert DiBlasi

**Comment by purplecones** [comment]
Thanks @sunright ! I'm glad you find it useful. @sunright was kind enough to provide a fix for your issue. Try now and let me know if it works for you on Safari 10.1.
